In [ ]:
import torch

x = torch.tensor(2.0,requires_grad = True)
y = x**2

y.backward()

print(x.grad)

tensor(4.)


`torch.tensor(2.0,requires_grad = True)`
- 2.0: x의 실제 값 
- requires_ grad = True : 편미분 값을 저장할 공간을 만들까요? jonna 편리하겠지? 근데 메모리도 처먹겠지?    

`y.backward()`   
자동으로 **x.grad**에 **dy/dx**값 저장. x**2를 미분한 **2*x에 x의 값인 2.0이 2*x에 대입되어 4.0이 x.grad에 드감.

In [3]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 2 * x
y.backward()

print(x.grad)

tensor(6.)


In [12]:
import torch

x = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],requires_grad=True)
y = x**3
y.sum().backward()
print(x.grad)

tensor([[  3.,  12.,  27.],
        [ 48.,  75., 108.]])


---
## 🏋️ 연습 문제

직접 풀어보고 `backward()`로 답을 확인해보세요!

### 문제 1. 기본 미분
$y = 3x^2 + 5x - 7$ 일 때, $x = 2$에서 $\frac{dy}{dx}$ 값은?

**힌트**: $\frac{dy}{dx} = 6x + 5$

In [14]:
# 문제 1 풀이 공간
import torch

x = torch.tensor(2.0, requires_grad=True)
# y = ???  # 여기에 수식 작성
y = 3*x**2 + 5*x - 7
# y.backward()
y.backward()
# print(f"dy/dx at x=2: {x.grad}")  # 정답: 17.0
print(x.grad)

tensor(17.)


### 문제 2. 지수함수 미분
$y = e^{2x}$ 일 때, $x = 1$에서 $\frac{dy}{dx}$ 값은?

**힌트**: $\frac{d}{dx}e^{2x} = 2e^{2x}$, `torch.exp()` 사용

In [15]:
# 문제 2 풀이 공간
import torch

x = torch.tensor(1.0, requires_grad=True)
# y = ???  # torch.exp() 사용
y = torch.exp(2*x)
# y.backward()
y.backward()
# print(f"dy/dx at x=1: {x.grad}")  # 정답: 약 14.78 (2*e^2)
print(x.grad)

tensor(14.7781)


### 문제 3. 삼각함수 미분
$y = \sin(x) + \cos(x)$ 일 때, $x = 0$에서 $\frac{dy}{dx}$ 값은?

**힌트**: $\frac{d}{dx}\sin(x) = \cos(x)$, $\frac{d}{dx}\cos(x) = -\sin(x)$

In [17]:
# 문제 3 풀이 공간
import torch

x = torch.tensor(0.0, requires_grad=True)
# y = ???  # torch.sin(), torch.cos() 사용
y = torch.sin(x)+torch.cos(x)
# y.backward()
y.backward()
# print(f"dy/dx at x=0: {x.grad}")  # 정답: 1.0 (cos(0) - sin(0) = 1 - 0)
print(x.grad)

tensor(1.)


### 문제 4. 편미분 (2변수)
$z = x^2 + xy + y^2$ 일 때, $(x, y) = (1, 2)$에서 $\frac{\partial z}{\partial x}$와 $\frac{\partial z}{\partial y}$ 값은?

**힌트**: 
- $\frac{\partial z}{\partial x} = 2x + y$  
- $\frac{\partial z}{\partial y} = x + 2y$

In [18]:
# 문제 4 풀이 공간
import torch

x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
# z = ???  # x, y 모두 사용하는 수식
z = x**2 + x*y + y**2
# z.backward()
z.backward()
# print(f"∂z/∂x at (1,2): {x.grad}")  # 정답: 4.0 (2*1 + 2)
print(x.grad)
# print(f"∂z/∂y at (1,2): {y.grad}")  # 정답: 5.0 (1 + 2*2)
print(y.grad)

tensor(4.)
tensor(5.)


### 문제 5. 연쇄 법칙 (Chain Rule) 🔥
$y = (2x + 1)^3$ 일 때, $x = 1$에서 $\frac{dy}{dx}$ 값은?

**힌트**: 연쇄 법칙! $\frac{dy}{dx} = 3(2x+1)^2 \cdot 2 = 6(2x+1)^2$

In [21]:
# 문제 5 풀이 공간
import torch

x = torch.tensor(1.0, requires_grad=True)
# y = ???  # (2x + 1)^3
y = (2*x + 1) ** 3
# y.backward()
y.backward()
# print(f"dy/dx at x=1: {x.grad}")  # 정답: 54.0 (6 * 3^2 = 6 * 9)
print(f"{x.grad}")

54.0


---
## 📝 정답 확인

스스로 풀어본 후 아래 정답을 확인하세요!

In [20]:
# ========== 정답 코드 ==========
import torch

print("=" * 50)
print("문제 1: y = 3x² + 5x - 7, x=2")
x1 = torch.tensor(2.0, requires_grad=True)
y1 = 3*x1**2 + 5*x1 - 7
y1.backward()
print(f"정답: {x1.grad}")  # 17.0

print("\n" + "=" * 50)
print("문제 2: y = e^(2x), x=1")
x2 = torch.tensor(1.0, requires_grad=True)
y2 = torch.exp(2*x2)
y2.backward()
print(f"정답: {x2.grad:.4f}")  # 14.7781

print("\n" + "=" * 50)
print("문제 3: y = sin(x) + cos(x), x=0")
x3 = torch.tensor(0.0, requires_grad=True)
y3 = torch.sin(x3) + torch.cos(x3)
y3.backward()
print(f"정답: {x3.grad}")  # 1.0

print("\n" + "=" * 50)
print("문제 4: z = x² + xy + y², (x,y)=(1,2)")
x4 = torch.tensor(1.0, requires_grad=True)
y4 = torch.tensor(2.0, requires_grad=True)
z4 = x4**2 + x4*y4 + y4**2
z4.backward()
print(f"∂z/∂x = {x4.grad}")  # 4.0
print(f"∂z/∂y = {y4.grad}")  # 5.0

print("\n" + "=" * 50)
print("문제 5: y = (2x + 1)³, x=1")
x5 = torch.tensor(1.0, requires_grad=True)
y5 = (2*x5 + 1)**3
y5.backward()
print(f"정답: {x5.grad}")  # 54.0

문제 1: y = 3x² + 5x - 7, x=2
정답: 17.0

문제 2: y = e^(2x), x=1
정답: 14.7781

문제 3: y = sin(x) + cos(x), x=0
정답: 1.0

문제 4: z = x² + xy + y², (x,y)=(1,2)
∂z/∂x = 4.0
∂z/∂y = 5.0

문제 5: y = (2x + 1)³, x=1
정답: 54.0


---
# 🧠 신경망 기초 (nn.Module)

## 신경망이란?
- 입력 → **가중치 연산** → 출력
- 학습 = 가중치(weight)와 편향(bias)을 최적화하는 과정

## PyTorch 신경망 핵심 구성요소
| 구성요소 | 설명 | 예시 |
|----------|------|------|
| `nn.Module` | 모든 신경망의 부모 클래스 | 모델 정의 시 상속 |
| `nn.Linear` | 완전연결층 (Fully Connected) | `nn.Linear(10, 5)` |
| `nn.ReLU` | 활성화 함수 | 비선형성 추가 |
| `nn.Sequential` | 레이어 순차 연결 | 간단한 모델 구성 |

## 1. nn.Linear (완전연결층) 이해하기

$y = xW^T + b$

- **x**: 입력 (input_features)
- **W**: 가중치 행렬 (weight)
- **b**: 편향 (bias)

In [22]:
import torch
import torch.nn as nn

# nn.Linear(입력 크기, 출력 크기)
linear = nn.Linear(3, 2)  # 3개 입력 → 2개 출력

print("=== nn.Linear 구조 ===")
print(f"Weight shape: {linear.weight.shape}")  # (2, 3)
print(f"Bias shape: {linear.bias.shape}")      # (2,)
print(f"\nWeight:\n{linear.weight}")
print(f"\nBias: {linear.bias}")

# 입력 데이터 (배치 크기 1, 특성 3개)
x = torch.tensor([[1.0, 2.0, 3.0]])
print(f"\n입력 x: {x}, shape: {x.shape}")

# 순전파 (forward)
output = linear(x)
print(f"출력: {output}, shape: {output.shape}")

=== nn.Linear 구조 ===
Weight shape: torch.Size([2, 3])
Bias shape: torch.Size([2])

Weight:
Parameter containing:
tensor([[-0.2372, -0.0321,  0.0847],
        [-0.2511,  0.3541, -0.5359]], requires_grad=True)

Bias: Parameter containing:
tensor([ 0.1451, -0.1834], requires_grad=True)

입력 x: tensor([[1., 2., 3.]]), shape: torch.Size([1, 3])
출력: tensor([[ 0.0977, -1.3339]], grad_fn=<AddmmBackward0>), shape: torch.Size([1, 2])


## 2. 활성화 함수 (Activation Functions)

신경망에 **비선형성**을 추가! 없으면 아무리 레이어 쌓아도 선형 변환일 뿐.

| 함수 | 수식 | 특징 |
|------|------|------|
| ReLU | $\max(0, x)$ | 가장 많이 사용 |
| Sigmoid | $\frac{1}{1+e^{-x}}$ | 0~1 출력, 이진분류 |
| Tanh | $\frac{e^x - e^{-x}}{e^x + e^{-x}}$ | -1~1 출력 |
| Softmax | $\frac{e^{x_i}}{\sum e^{x_j}}$ | 다중분류, 확률 출력 |

In [ ]:
import torch
import torch.nn as nn

x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

print("입력 x:", x)
print("\n=== 활성화 함수 비교 ===")

# ReLU: 음수 → 0, 양수 → 그대로
relu = nn.ReLU()
print(f"ReLU:    {relu(x)}")

# Sigmoid: 0~1 사이로 압축
sigmoid = nn.Sigmoid()
print(f"Sigmoid: {sigmoid(x)}")

# Tanh: -1~1 사이로 압축
tanh = nn.Tanh()
print(f"Tanh:    {tanh(x)}")

# Softmax: 합이 1이 되는 확률 분포
softmax = nn.Softmax(dim=0)
print(f"Softmax: {softmax(x)}")
print(f"Softmax 합: {softmax(x).sum()}")  # 1.0

## 3. nn.Sequential로 간단한 신경망 만들기

레이어들을 순서대로 쌓는 가장 쉬운 방법!

In [ ]:
import torch
import torch.nn as nn

# 간단한 신경망: 4 → 8 → 4 → 1
model = nn.Sequential(
    nn.Linear(4, 8),    # 입력층 → 은닉층1
    nn.ReLU(),          # 활성화
    nn.Linear(8, 4),    # 은닉층1 → 은닉층2
    nn.ReLU(),          # 활성화
    nn.Linear(4, 1)     # 은닉층2 → 출력층
)

print("=== 모델 구조 ===")
print(model)

# 테스트 입력
x = torch.randn(1, 4)  # 배치 1, 특성 4개
print(f"\n입력: {x}")
print(f"출력: {model(x)}")

## 4. nn.Module로 커스텀 신경망 만들기 ⭐

실제로 가장 많이 사용하는 방법! 더 유연하고 복잡한 모델 가능.

In [ ]:
import torch
import torch.nn as nn

class MyNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()  # 부모 클래스 초기화 (필수!)
        
        # 레이어 정의
        self.layer1 = nn.Linear(4, 8)
        self.layer2 = nn.Linear(8, 4)
        self.layer3 = nn.Linear(4, 1)
        self.relu = nn.ReLU()
    
    def forward(self, x):
        # 순전파 정의 (데이터가 어떻게 흐르는지)
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.relu(x)
        x = self.layer3(x)
        return x

# 모델 생성
model = MyNeuralNetwork()
print("=== 커스텀 모델 구조 ===")
print(model)

# 테스트
x = torch.randn(1, 4)
output = model(x)  # model.forward(x) 호출됨
print(f"\n입력 shape: {x.shape}")
print(f"출력 shape: {output.shape}")
print(f"출력: {output}")

## 5. 모델의 파라미터 확인하기

학습 가능한 파라미터(weight, bias)들을 확인!

In [ ]:
# 파라미터 이름과 shape 확인
print("=== 모델 파라미터 ===")
for name, param in model.named_parameters():
    print(f"{name}: {param.shape}")

# 총 파라미터 수 계산
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\n총 파라미터 수: {total_params}")
print(f"학습 가능 파라미터: {trainable_params}")

## 6. 손실 함수 (Loss Function)

예측값과 실제값의 차이를 측정! 이걸 최소화하는 게 학습의 목표.

| 손실 함수 | 용도 | PyTorch |
|-----------|------|---------|
| MSE | 회귀 | `nn.MSELoss()` |
| CrossEntropy | 분류 | `nn.CrossEntropyLoss()` |
| BCE | 이진분류 | `nn.BCELoss()` |

In [ ]:
import torch
import torch.nn as nn

# 예측값과 실제값
prediction = torch.tensor([2.5, 0.0, 2.1])
target = torch.tensor([3.0, -0.5, 2.0])

# MSE Loss (평균 제곱 오차)
mse_loss = nn.MSELoss()
loss = mse_loss(prediction, target)
print(f"MSE Loss: {loss}")

# 수동 계산 확인: ((2.5-3)^2 + (0-(-0.5))^2 + (2.1-2)^2) / 3
manual = ((2.5-3)**2 + (0-(-0.5))**2 + (2.1-2)**2) / 3
print(f"수동 계산: {manual}")

## 7. 옵티마이저 (Optimizer)

손실을 줄이는 방향으로 파라미터를 업데이트!

$\theta_{new} = \theta_{old} - lr \times \nabla Loss$

| 옵티마이저 | 특징 |
|------------|------|
| SGD | 기본, 단순 |
| Adam | 가장 많이 사용! 적응적 학습률 |
| RMSprop | RNN에서 자주 사용 |

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# 간단한 모델
model = nn.Linear(2, 1)

# 옵티마이저 생성 (모델의 파라미터와 학습률 전달)
optimizer = optim.SGD(model.parameters(), lr=0.01)
# optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adam도 많이 씀!

print("=== 옵티마이저 ===")
print(optimizer)

## 8. 🔥 학습 루프 (Training Loop) - 핵심!

신경망 학습의 핵심 과정:
```
1. 순전파 (Forward)     → 예측값 계산
2. 손실 계산 (Loss)     → 얼마나 틀렸나?
3. 역전파 (Backward)    → 기울기 계산
4. 파라미터 업데이트    → 가중치 수정
```

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# === 데이터 준비 (y = 2x + 1 학습시키기) ===
X = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
y = torch.tensor([[3.0], [5.0], [7.0], [9.0], [11.0]])  # y = 2x + 1

# === 모델 정의 ===
model = nn.Linear(1, 1)  # 입력 1개, 출력 1개

# === 손실 함수 & 옵티마이저 ===
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# === 학습 루프 ===
print("=== 학습 시작 ===")
for epoch in range(100):
    # 1. 순전파: 예측값 계산
    predictions = model(X)
    
    # 2. 손실 계산
    loss = criterion(predictions, y)
    
    # 3. 역전파: 기울기 계산
    optimizer.zero_grad()  # ⚠️ 중요! 이전 기울기 초기화
    loss.backward()
    
    # 4. 파라미터 업데이트
    optimizer.step()
    
    # 10번마다 출력
    if (epoch + 1) % 20 == 0:
        print(f"Epoch [{epoch+1}/100], Loss: {loss.item():.4f}")

# === 학습 결과 확인 ===
print("\n=== 학습된 파라미터 ===")
print(f"Weight (기울기): {model.weight.item():.4f}")  # 2에 가까워야 함
print(f"Bias (절편): {model.bias.item():.4f}")       # 1에 가까워야 함

# 새로운 값 예측
test_x = torch.tensor([[6.0]])
print(f"\nx=6 예측값: {model(test_x).item():.2f} (정답: 13)")